# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f77f63dcaa6fb5bc4918ca732546248d8b22af7101bcb702c13a2ff9f0846abd1b074889bbec4fb18eb31640d6ac9f8411a6c18b0c543220de168a1eec653fa

test:
  secret_key_base: 7fbe3a102aa20c25238d1b82d6099d1bb0885cd8bfebd68c854c6184143718e5f3cf855ad1be53ecb9c15f68d5d159514dfcd196781e18624c97f480924b9a92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
